@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri May 05 23:18:51 +0330 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto b3d5162a266a4eb191fedb35e61b0802 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot MUX4x2TB_behav xil_defaultlib.MUX4x2TB -log elaborate.log"
call xelab  -wto b3d5162a266a4eb191fedb35e61b0802 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot MUX4x2TB_behav xil_defaultlib.MUX4x2TB -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
